
name: delivery
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.17.0
  flutter_svg: ^2.0.9
  circular_menu: ^2.0.1
  font_awesome_flutter: ^10.6.0
  image_picker: ^0.8.4+4
  firebase_core: ^2.16.0
  http: ^0.13.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_map: ^3.1.0
  latlng: ^0.2.0
  latlong2: ^0.8.1
  http_parser: ^4.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  user_repository:
    path: packages/user_repository
  delivery_repository:
    path: packages/delivery_repository
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^17.0.1
  flutter_timezone: ^1.0.8
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  animate_do: ^3.0.2
  advance_notification: ^1.0.6
  badges: ^2.0.3
  line_icons: ^2.0.3
  bottom_bar_matu: ^1.3.0

  open_street_map_search_and_pick: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans-Bold.ttf
        - asset: assets/fonts/AlegreyaSans-Medium.ttf